openapi: 3.0.0
info:
  title: graph-traveral
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /dfs:
    parameters: []
    post:
      responses:
        '200':
          $ref: '#/components/responses/TraversalResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TraversalRequest'
        description: Request graph traversal via depth first search
components:
  schemas:
    Graph:
      title: Graph in a Request
      type: object
      x-examples:
        Example Graph Request:
          - - '1'
            - '2'
          - - '1'
            - '3'
          - - '2'
            - '4'
          - - '3'
            - '9'
          - - '3'
            - '10'
      properties:
        edges:
          type: array
          items:
            type: array
            items: {}
      required:
        - edges
    FullGraph:
      type: object
      properties:
        nodes:
          type: array
          items:
            type: string
        edges:
          type: array
          uniqueItems: true
          items:
            type: object
            properties:
              src:
                type: string
                minLength: 1
              dst:
                type: string
                minLength: 1
              weight:
                type: number
            required:
              - src
              - dst
              - weight
      required:
        - nodes
        - edges
      x-examples:
        example-1:
          nodes:
            - '1'
            - '2'
            - '3'
            - '4'
            - '9'
            - '10'
            - '5'
            - '6'
            - '7'
            - '8'
            - '11'
          edges:
            - src: '1'
              dst: '2'
              weight: 1
            - src: '1'
              dst: '3'
              weight: 1
            - src: '2'
              dst: '4'
              weight: 1
            - src: '3'
              dst: '9'
              weight: 1
            - src: '3'
              dst: '10'
              weight: 1
            - src: '4'
              dst: '5'
              weight: 1
            - src: '4'
              dst: '6'
              weight: 1
            - src: '5'
              dst: '7'
              weight: 1
            - src: '6'
              dst: '2'
              weight: 1
            - src: '6'
              dst: '9'
              weight: 1
            - src: '6'
              dst: '7'
              weight: 1
            - src: '7'
              dst: '8'
              weight: 1
            - src: '7'
              dst: '11'
              weight: 1
            - src: '9'
              dst: '10'
              weight: 1
            - src: '10'
              dst: '7'
              weight: 1
            - src: '11'
              dst: '10'
              weight: 1
    TraversalRequest:
      type: object
      x-examples:
        Example Graph Request:
          start: '1'
          graph:
            - - '1'
              - '2'
            - - '1'
              - '3'
            - - '2'
              - '4'
            - - '3'
              - '9'
            - - '3'
              - '10'
      properties:
        graph:
          $ref: '#/components/schemas/Graph'
        start:
          type: string
      required:
        - graph
        - start
    GraphDistances:
      type: array
      description: ''
      minItems: 1
      uniqueItems: true
      x-examples:
        example-1:
          - destination: '1'
            distance: 0
          - destination: '2'
            distance: 1
          - destination: '3'
            distance: 1
          - destination: '4'
            distance: 5
      items:
        type: object
        properties:
          destination:
            type: string
            minLength: 1
          distance:
            type: number
        required:
          - destination
          - distance
  responses:
    TraversalResponse:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              start:
                type: string
              distances:
                $ref: '#/components/schemas/GraphDistances'
              graph:
                $ref: '#/components/schemas/FullGraph'
            required:
              - start
              - distances
              - graph
          examples:
            example-1:
              value:
                start: '1'
                graph:
                  nodes:
                    - '1'
                    - '2'
                    - '3'
                    - '4'
                    - '9'
                    - '10'
                    - '5'
                    - '6'
                    - '7'
                    - '8'
                    - '11'
                  edges:
                    - src: '1'
                      dst: '2'
                      weight: 1
                    - src: '1'
                      dst: '3'
                      weight: 1
                    - src: '2'
                      dst: '4'
                      weight: 1
                    - src: '3'
                      dst: '9'
                      weight: 1
                    - src: '3'
                      dst: '10'
                      weight: 1
                    - src: '4'
                      dst: '5'
                      weight: 1
                    - src: '4'
                      dst: '6'
                      weight: 1
                    - src: '5'
                      dst: '7'
                      weight: 1
                    - src: '6'
                      dst: '2'
                      weight: 1
                    - src: '6'
                      dst: '9'
                      weight: 1
                    - src: '6'
                      dst: '7'
                      weight: 1
                    - src: '7'
                      dst: '8'
                      weight: 1
                    - src: '7'
                      dst: '11'
                      weight: 1
                    - src: '9'
                      dst: '10'
                      weight: 1
                    - src: '10'
                      dst: '7'
                      weight: 1
                    - src: '11'
                      dst: '10'
                      weight: 1
                distances:
                  - destination: '1'
                    distance: 0
                  - destination: '2'
                    distance: 1
                  - destination: '3'
                    distance: 1
                  - destination: '4'
                    distance: 2
                  - destination: '5'
                    distance: 3
                  - destination: '6'
                    distance: 3
                  - destination: '7'
                    distance: 3
                  - destination: '8'
                    distance: 4
                  - destination: '9'
                    distance: 2
                  - destination: '10'
                    distance: 2
                  - destination: '11'
                    distance: 4
    ValidationError:
      description: Invalid Request data
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                minLength: 1
              errors:
                type: array
                uniqueItems: true
                minItems: 1
                items:
                  required:
                    - path
                    - message
                    - errorCode
                  properties:
                    path:
                      type: string
                      minLength: 1
                    message:
                      type: string
                      minLength: 1
                    errorCode:
                      type: string
                      minLength: 1
            required:
              - message
              - errors
